### ISSUE TITLE
Crash on World Gen

### ISSUE THREAD

**Issue by MoonlightSystem** [cassiancc/Simply-Infinite#1]
[crash report](https://github.com/ConGodsted/Simply-Infinite/files/12888170/crash-2023-10-12_17.18.58-client.txt)
Happens on latest version(1.0.2)

**Comment by cassiancc** [comment]
I've removed Dynamic FPS for 1.0.3, infinite seems to have changed some elements of the rendering API. I'll look into porting it myself when I get the chance.
