### ISSUE TITLE
[Mod Suggestion] Voxel Map

### ISSUE THREAD

**Issue by NicKnack819** [cassiancc/Simply-Infinite#2]
**Mod Suggestion**: VoxelMap
**Why**: A Very Helpful Mini-map Mod Good For Navigating The Dimensions
**Mod Link**: [(Link Here)](<https://www.curseforge.com/minecraft/mc-mods/voxelmap/files/2918814>)

Side Note: I am glad to see someone made and published a more reliable pack than the one I posted to the [Snapshot's Reddit](<https://www.reddit.com/r/20w14infinite/comments/12hsqi9/working_updated_mod_setup_for_this_snapshot/>) quite a while ago... So just wanted to say keep the Flame burning and Uphold the Legacy of the Limitless Possibilities!

**Comment by cassiancc** [comment]
Thanks for the suggestion! The pack you posted was a major inspiration for Simply Infinite, and I really appreciate the support.

Interesting sidenote: the version on CurseForge labelled as 20w14infinite crashes, but the one for 20w13ab works. This version is strange sometimes.

**Comment by NicKnack819** [comment]
> Thanks for the suggestion! The pack you posted was a major inspiration for Simply Infinite, and I really appreciate the support.
> 
> Interesting sidenote: the version on CurseForge labelled as 20w14infinite crashes, but the one for 20w13ab works. This version is strange sometimes.

Yup, realized that after the fact forgot to change it here I guess... And I'm honored I was able to inspire this masterpiece of a pack! honestly glad someone was able to raise the standard of what I had put out there.
