### ISSUE TITLE
Some More Mod Suggestions

### ISSUE THREAD

**Issue by NicKnack819** [cassiancc/Simply-Infinite#5]
Main Suggestion:
- [1.15 Dragon Hitbox Fix](https://modrinth.com/mod/dragon-hitbox-fix/versions)
  - Why: Fixes the Hitbox of the dragon in this version

Optional:
- [FullscreeNO](https://modrinth.com/mod/fullscreeno/version/1.0.0)
  - Why: No forced full screen on boot
- [Music Duration Reducer](https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer/files/3055659)
  - Why: It's Just A nice mod that allows the user to reduce the duration in-between the in game music.

Mainly had the 3 Client Mod Suggestions as well as Server Mod Suggestion but not sure if it's okay to share since the file doesn't have any link to credit it seems like...
Mod is `NoCMD by Teak1` according to the file data all it did was disable commands like "/warp" for the non-op players... The only version I have for it is from the old server download from Alan Foster Previously known as AlanfinityLive on Twitch

**Comment by cassiancc** [comment]
Thanks for the suggestions! I've added all three and will release shortly. I haven't been able to find a trace of NoCMD on the internet, so I'd be hesitant to include it for licensing reasons. I could try recreating it myself, but no promises on a timeline for that, as I haven't worked with commands before.

**Comment by NicKnack819** [comment]
you added an extra k in my name in the change log btw lol

**Comment by NicKnack819** [comment]
also one more mod [config backuper](https://modrinth.com/mod/configbackuper/version/Y4xAiwac) would set the max config backups to like 4 or 6
